Use core number as the default concurrent compile task number in x.py
apache/kvrocks pull request #1125
Opened 2022-11-15 13:07 UTC by PragmaTwice

`4` is not a good value for default concurrent compile task number. 

In devices which core number is less than 4 (like vm of github actions), it can make the compile time even longer than `-j $(nproc)`, and if ore number is more than 4, it will also take longer than `-j $(nproc)` in normal situation.

2022-11-15 13:18 UTC, git-hulk commented
I like this change

2022-11-15 13:18 UTC, git-hulk approved these changes

2022-11-15 13:18 UTC, tisonkun approved these changes
Thanks for your contribution!

2022-11-15 14:42 UTC, tisonkun commented
https://app.travis-ci.com/github/apache/incubator-kvrocks/jobs/588512318 Compilation failed. Please take a look @PragmaTwice .

2022-11-15 14:56 UTC, PragmaTwice commented
> https://app.travis-ci.com/github/apache/incubator-kvrocks/jobs/588512318 Compilation failed. Please take a look @PragmaTwice .

I notice that `cpu_count` returns 80 in travis ci, and then `make -j80` is run, causing memory overflow. It is weird.

2022-11-15 15:07 UTC, git-hulk commented
> > https://app.travis-ci.com/github/apache/incubator-kvrocks/jobs/588512318 Compilation failed. Please take a look @PragmaTwice .
> 
> I notice that `cpu_count` returns `80` in travis ci, and then `make -j80` is run, causing OOM. It is weird.

Maybe the `getcpu()` retrieves the number of physical host cores, but the building process is running in docker environment with limited resource.

2022-11-15 15:33 UTC, PragmaTwice commented
> > > https://app.travis-ci.com/github/apache/incubator-kvrocks/jobs/588512318 Compilation failed. Please take a look @PragmaTwice .
> > 
> > 
> > I notice that `cpu_count` returns `80` in travis ci, and then `make -j80` is run, causing OOM. It is weird.
> 
> Maybe the `getcpu()` retrieves the number of physical host cores, but the building process is running in the docker environment with limited resources.

I also suspect so. But I do not know how to retrieve the correct core numbers. :rofl:

2022-11-15 16:47 UTC, tanruixiang commented
> I also suspect so. But I do not know how to retrieve the correct core number. 🤣

Try this? @PragmaTwice 
https://donghao.org/2022/01/20/how-to-get-the-number-of-cpu-cores-inside-a-container/

2022-11-16 03:33 UTC, PragmaTwice commented
> > I also suspect so. But I do not know how to retrieve the correct core number. 🤣
> 
> Try this? @PragmaTwice https://donghao.org/2022/01/20/how-to-get-the-number-of-cpu-cores-inside-a-container/

Thanks! I will try it. It would be nice if it can be cross-platform (e.g. linux/mac).

2022-11-16 03:37 UTC, PragmaTwice commented
```
$ cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us
cat: /sys/fs/cgroup/cpu/cpu.cfs_quota_us: No such file or directory
```

It is weird. It always reports "no such file" in my local host machine and docker container.

2022-11-16 03:41 UTC, PragmaTwice commented
I think it is hard to find a sound & robust way to retrieve current core number with respect to cpuset. 

`psutil` did this, but its implementation is complex.

2022-11-16 03:46 UTC, git-hulk commented
> I think it is hard to find a sound & robust way to retrieve current core number with respect to cpuset.
> 
> `psutil` did this, but its implementation is complex.

It should be not worth to do that if we need to import a new module or add too much complexity.

2022-11-16 03:49 UTC, tisonkun requested changes
What if we simply remove this argument from required?

In the CI workflow, we can calculate CPU with shell command, and users can leverage they own utils to calculate it. If parallelism is not important for the use case, simple omit the config.

2022-11-16 03:56 UTC, tanruixiang commented
> ```
> $ cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us
> cat: /sys/fs/cgroup/cpu/cpu.cfs_quota_us: No such file or directory
> ```
> 
> It is weird. It always reports "no such file" in my local host machine and docker container.

In cgroup2, it seems to have been migrated to `cpu.max`.

https://stackoverflow.com/questions/65551215/get-docker-cpu-memory-limit-inside-container/65554131#65554131

2022-11-22 03:41 UTC, closed without merging