Fix -Wreturn-std-move wanring
apache/kvrocks pull request #1613
Opened 2023-07-27 15:40 UTC by enjoy-binbin

When building, the following warning appears:
```
warning: local variable 's' will be copied despite being returned by name [-Wreturn-std-move]
note: call 'std::move' explicitly to avoid copying
```

2023-07-27 15:41 UTC, enjoy-binbin commented
i am not very familiar with it, so hopefully it is a right fix

2023-07-27 15:41 UTC, torwig approved these changes

2023-07-28 00:18 UTC, PragmaTwice requested changes
Move a local variable to return is not a good way in C++ (especially modern C++), since:
1. the move in return is already implicit in c++ standard
2. it will prevent NRVO (named return value optimization).

refer to https://stackoverflow.com/questions/14856344/when-should-stdmove-be-used-on-a-function-return-value.

2023-07-30 15:07 UTC, enjoy-binbin commented
thanks for the link. so these warnings are false positives? do we have any other option to ignore it?

2023-07-30 15:19 UTC, mapleFU commented
I guess this would be fixed with a higher version of compiler

2023-07-31 02:37 UTC, enjoy-binbin commented
> By the way, would you mind print the version of clang and clang-tidy?

sure, i will take a look when i get home. (i am using different PC when i am working)

2023-07-31 17:15 UTC, enjoy-binbin commented
```
$ clang -v
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

2023-07-31 20:20 UTC, PragmaTwice commented
Seems your clang version is too old. Apple Clang 12 is based on LLVM/Clang 10, but the latest version of LLVM is 16.

BTW I recommend that you use LLVM/Clang rather than Apple Clang.

2023-08-28 10:12 UTC, mapleFU commented
Can this patch be closed? Since it's no problem in our current C++ version?

2023-08-28 10:17 UTC, enjoy-binbin commented
ohh, right, since there is no real issue, i am closing it.
I forgot to sync, i am having some env trouble in my laptop so i haven't found the time to verify it

2023-08-28 10:17 UTC, closed without merging