fix(json): int64 overflow in JSON numop
apache/kvrocks pull request #2340
Opened 2024-05-30 01:02 UTC by jackyyyyyssss

Json_val. NumOp only considers cases where the value of the double type is out of bounds, and does not consider cases where the int64 type is out of bounds. If the int64 type is out of bounds, it will cause the lambda function to exit abnormally and not catch. This exception will cause the kvrocks to crash
<img width="754" alt="27319d3236f39a914025911dac65157" src="https://github.com/apache/kvrocks/assets/127465317/97ad041d-3452-4a13-abe0-0cca0a9809b9">
<img width="839" alt="ff70eb032f10ad79a3a379996df76fc" src="https://github.com/apache/kvrocks/assets/127465317/2379f9bf-bf8f-4608-a3f4-6de3017ee99c">

2024-05-30 10:14 UTC, PragmaTwice commented
Thank you for your great finding.

2024-05-30 10:15 UTC, PragmaTwice commented on src/types/redis_json.cc
> +  }
I think it can be fixed in the JsonValue::NumOp. Here we can only fix for `value`, not the number inside the current json.

2024-05-31 07:51 UTC, jackyyyyyssss commented on src/types/redis_json.cc
> +  }
Thank you. Summarized all the situations to see if there were any omissions

2024-05-31 10:27 UTC, PragmaTwice commented on src/common/bit_util.h
> +}
This function looks very weird. What's `operation`? What's `1` here? Why `mul` is executed if `operation` is not 1?

Please remove it.

2024-05-31 10:28 UTC, PragmaTwice requested changes
Please just add a catch block. Try not to add any meaningless weird code.

2024-05-31 10:36 UTC, PragmaTwice commented on src/common/bit_util.h
> +}
Also, this function is totally wrong since the result is passed by value.

2024-05-31 10:42 UTC, jackyyyyyssss commented
> Please just add a catch block. Try not to add any meaningless weird code.

Simple catch doesn't seem to work, some overflow cases can return results that don't meet expectations without throwing exceptions  
For example, 9223372036854775806<std:: numericlimits:: max()  +20 is a negative number and will not throw an exception

2024-05-31 11:05 UTC, PragmaTwice commented
> > Please just add a catch block. Try not to add any meaningless weird code.
> 
> Simple catch doesn't seem to work, some overflow cases can return results that don't meet expectations without throwing exceptions For example, 9223372036854775806<std:: numericlimits:: max() +20 is a negative number and will not throw an exception

It can be actually well defined. It follows the [two's complement](https://en.m.wikipedia.org/wiki/Two's_complement). So generally we can leave it as is until we make a big number implementation available.

2024-05-31 11:13 UTC, jackyyyyyssss commented
> So generally we can leave it as is until we make a big number implementation available.

What do you mean by directly adding a catch (const jsoncons:: json_runtime_error<std:: runtime_error>e){
Return {Status:: NotOK, e.what()};
}Is that enough for this ？

2024-05-31 11:16 UTC, PragmaTwice commented
> > So generally we can leave it as is until we make a big number implementation available.
> 
> What do you mean by directly adding a catch (const jsoncons:: json_runtime_error<std:: runtime_error>e){ Return {Status:: NotOK, e.what()}; }Is that enough for this ？

Yeah, just preventing kvrocks from crash is enough.

2024-05-31 12:04 UTC, PragmaTwice commented
Sorry I looked into this problem a little bit, and seems it's a design issue inside the NumOp method.

I opened a PR to address it (#2345).

But anyway thank you very much for your great finding and effort.

2024-05-31 13:29 UTC, jackyyyyyssss commented
> Sorry I looked into this problem a little bit, and seems it's a design issue inside the NumOp method.
> 
> I opened a PR to address it (#2345).
> 
> But anyway thank you very much for your great finding and effort.

You have made the same changes to the visual and redis stack processing, and have learned a lot

2024-05-31 13:29 UTC, closed without merging