Metadata and subkey column family share a singleblock cache
apache/kvrocks pull request #365
Opened 2021-09-23 14:43 UTC by caipengbo

By default, `metadata` Column Family and `subkey` Column Family have their own block cache, so block cache must be allocated in advance for the two CFs. 
It is not possible to predict the usage of the two CFs and allocate the optimal capacity for the two block caches, so we can provide a configuration item that specifies whether the two CFs should share a single block cache (see rocksdb [Wiki](https://github.com/facebook/rocksdb/wiki/Memory-usage-in-RocksDB#indexes-and-filter-blocks)).

Regarding this configuration item, although it is not an item for Rocksdb Option, it is related to Rocksdb, so I gave it a name prefixed with `rocksdb.`.

2021-09-23 15:04 UTC, git-hulk commented
wow, really a good feature.

2021-09-24 02:40 UTC, ShooterIT requested changes

2021-09-24 02:40 UTC, ShooterIT commented on src/storage.cc
> +}  // namespace Engine
```suggestion
}  // namespace Engine

```

2021-09-24 02:40 UTC, ShooterIT commented on src/storage.cc
> +  if (share_metadata_and_subkey_block_cache) {
```suggestion
  if (config_->RocksDB.share_metadata_and_subkey_block_cache) {
```

2021-09-24 02:40 UTC, ShooterIT commented on src/storage.cc
> +
```suggestion
```

2021-09-24 04:18 UTC, ShooterIT approved these changes

2021-09-25 03:44 UTC, git-hulk approved these changes
LGTM

2021-09-25 03:44 UTC, merged