use unique_ptr in src/server.h
apache/kvrocks pull request #673
Opened 2022-06-25 16:55 UTC by zz-jason

Signed-off-by: Jian Zhang <zjsariel@gmail.com>

2022-06-25 19:56 UTC, tisonkun commented
This patch can be blocked by #645 as `missingInclude` is tricky to address. See also https://github.com/apache/incubator-kvrocks/pull/645#issuecomment-1162042973.

2022-06-26 01:30 UTC, tisonkun requested changes
@zz-jason There're other failure in CI tasks. Please make sure that with you patch you can still compile kvrocks and pass `./cppcheck.sh` at least.

2022-06-26 02:47 UTC, PragmaTwice commented on src/server.h
> +  class SlotImport *slot_import_;
```suggestion
  class SlotImport *slot_import_ = nullptr;
```
fix the cppcheck warning in CI.

2022-06-26 03:29 UTC, PragmaTwice commented
Could you remove `--suppress=noCopyConstructor:src/server.cc --suppress=noOperatorEq:src/server.cc` in `./cppcheck.sh` to make CI pass? Sorry for discommodity.

2022-06-26 03:52 UTC, zz-jason commented
I find the help message of `cppcheck` is:

```
--suppress=<spec>    Suppress warnings that match <spec>. The format of
                     <spec> is:
                     [error id]:[filename]:[line]
                     The [filename] and [line] are optional. If [error id]
                     is a wildcard '*', all error ids match.
```

Does `--suppress=noCopyConstructor:src/server.cc` mean to ignore the `noCopyConstructor` warning for `src/server.cc`?

2022-06-26 04:02 UTC, PragmaTwice commented
> I find the help message of `cppcheck` is:
> 
> ```
> --suppress=<spec>    Suppress warnings that match <spec>. The format of
>                      <spec> is:
>                      [error id]:[filename]:[line]
>                      The [filename] and [line] are optional. If [error id]
>                      is a wildcard '*', all error ids match.
> ```
> 
> Does `--suppress=noCopyConstructor:src/server.cc` mean to ignore the `noCopyConstructor` warning for `src/server.cc`?

Yeah, my guess is that the `noCopyConstructor` warning no longer appears because you changed the type of some of `Server`'s fields to `unique_ptr` (which has no copy ctor) so that `Server` can no longer copy constructible. 
At this point cppcheck reports `unmatchedSuppression` because we added an useless `-suppress`.
We will consider using clang tidy instead of cppcheck in the future.
```
src/server.cc:-1:0: information: Unmatched suppression: noCopyConstructor [unmatchedSuppression]
^
src/server.cc:-1:0: information: Unmatched suppression: noOperatorEq [unmatchedSuppression]
^
```
Actually you can add `--suppress=unmatchedSuppression` instead of remove anything.

2022-06-26 08:37 UTC, PragmaTwice approved these changes
LGTM

2022-06-26 09:41 UTC, tisonkun approved these changes
LGTM.

@git-hulk @PragmaTwice it seems we don't have `delete cluster_` to eliminate in this patch, did we leak memory previously on these field?

2022-06-26 10:17 UTC, PragmaTwice commented
> LGTM.
> 
> @git-hulk @PragmaTwice it seems we don't have `delete cluster_` to eliminate in this patch, did we leak memory previously on these field?

I also wonder that. 🤣

2022-06-26 12:36 UTC, git-hulk commented
@tisonkun @PragmaTwice Yes, we do leak this field even it wouldn't cause problem.

2022-06-26 12:36 UTC, git-hulk approved these changes

2022-06-26 14:41 UTC, git-hulk commented
Thanks for @zz-jason contribution, merging...

2022-06-26 14:41 UTC, merged