ci: add a label to trigger daily CI in PR
apache/kvrocks pull request #694
Opened 2022-06-29 10:24 UTC by GoGim1

close #665

2022-06-29 11:14 UTC, ShooterIT commented
cool, thanks

2022-06-29 11:17 UTC, tisonkun requested changes
This change doesn't work because pull_request event doesn't include label changes. See also https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#label.

Also I commented on #665 for an alternative - we may not implement the feature in this way.

2022-06-29 11:36 UTC, tisonkun reviewed
Sorry. I get it wrong that the condition should be event=pull_request + type=labeled.

However, the condition should be handled in `daily-ci.yaml`, where you can change `paths:` to `types: [labeled]`.

2022-06-29 11:36 UTC, tisonkun commented on .github/workflows/kvrocks.yaml
> +    if: contains(github.event.pull_request.labels.*.name, 'need-daily-CI')
```suggestion
    if: contains(github.event.pull_request.labels.*.name, 'needs-daily-ci')
```

2022-06-29 12:41 UTC, tisonkun commented
@GoGim1 I'm integrate this patch with a solution to #691.

2022-06-30 01:19 UTC, GoGim1 commented
thanks everyone!

2022-06-30 01:19 UTC, closed without merging